### ISSUE TITLE
Support for hierarchy of categories

### ISSUE THREAD

**Issue by day-jeff** [EddyLuten/mkdocs-categories-plugin#2]
Is it possilbe to define a hierarchy of categories so that each category page shows both pages directly assigned to it, as well as child categories? This is standard in mediawiki.

For example, given the following hierarchy, there will be a Boeing category page that shows both any pages directly assigned to the Boeing category, and it will show two child categories: 737 Max and 737-300.

Vehicles
--Airplanes
----Boeing
------737 Max
------737-300
----Airbus
------A320neo
------A380
--Cars
----Tesla
------Model 3
------Model Y
----Ford
------Explorer
------Focus

**Comment by EddyLuten** [comment]
Hi @day-jeff, apologies for not replying sooner. Yeah, this is entirely doable. I'll post an update on this issue once it's implemented.

**Comment by EddyLuten** [comment]
Resolved in version v0.3.0, now published to PyPI. Check out the README on how to use the syntax for subcategories.
